[package]
name = "boleto_utils"
version = "0.1.0"
edition = "2021"

authors = ["Fernando Sávio <admin@fsavio.dev>"]
description = "Utility library to work with brazilian payment slip (aka 'boleto')."
homepage = ""
repository = ""
license = "MIT"
keywords = ["barcode", "boleto"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
lazy_static = "1.4.0"
csv = "1.1.6"
clap = { version = "3.2.22", features = ["derive"] }
