[package]
name = "boleto_utils_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
boleto_utils = { path = ".." }

clap = { version = "3.2.22", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

[[bin]]
name = "boleto"
path = "src/boleto.rs"
doc = false
