extern crate csv;

use std::fmt;

use phf::phf_map;


static BANKS_INFO: phf::Map<u16, &'static str> = phf_map! {
    1_u16 => "Banco do Brasil S.A.",
    3_u16 => "Banco da Amazonia S.A.",
    4_u16 => "Banco do Nordeste do Brasil S.A.",
    7_u16 => "Banco Nacional de Desenvolvimento Economico e Social",
    10_u16 => "Credicoamo Crédito Rural Cooperativa",
    11_u16 => "Credit Suisse Hedging-Griffo Corretora de Valores S.A",
    12_u16 => "Banco Inbursa S.A.",
    14_u16 => "State Street Brasil S.A. - Banco Comercial",
    15_u16 => "UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.",
    16_u16 => "Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul",
    17_u16 => "BNY Mellon Banco S.A.",
    18_u16 => "Banco Tricury S.A.",
    21_u16 => "Banestes S.A. Banco do Estado do Espirito Santo",
    24_u16 => "Banco Bandepe S.A.",
    25_u16 => "Banco Alfa S.A.",
    29_u16 => "Banco Itaú Consignado S.A.",
    33_u16 => "Banco Santander (Brasil) S.A.",
    36_u16 => "Banco Bradesco BBI S.A.",
    37_u16 => "Banco do Estado do Pará S.A.",
    40_u16 => "Banco Cargill S.A.",
    41_u16 => "Banco do Estado do Rio Grande do Sul S.A.",
    47_u16 => "Banco do Estado de Sergipe S.A.",
    60_u16 => "Confidence Corretora de Câmbio S.A.",
    62_u16 => "Hipercard Banco Múltiplo S.A.",
    63_u16 => "Banco Bradescard S.A.",
    64_u16 => "Goldman Sachs do Brasil Banco Multiplo S.A.",
    65_u16 => "Banco Andbank (Brasil) S.A.",
    66_u16 => "Banco Morgan Stanley S.A.",
    69_u16 => "Banco Crefisa S.A.",
    70_u16 => "BRB - Banco de Brasilia S.A.",
    74_u16 => "Banco J. Safra S.A.",
    75_u16 => "Banco ABN AMRO S.A.",
    76_u16 => "Banco KDB do Brasil S.A.",
    77_u16 => "Banco Inter S.A.",
    78_u16 => "Haitong Banco de Investimento do Brasil S.A.",
    79_u16 => "Banco Original do Agronegócio S.A.",
    80_u16 => "B&T Corretora de Câmbio Ltda",
    81_u16 => "BancoSeguro S.A.",
    82_u16 => "Banco Topázio S.A.",
    83_u16 => "Banco da China Brasil S.A.",
    84_u16 => "Uniprime Norte do Paraná - Cooperativa de Economia e Crédito Mútuo dos Médicos",
    85_u16 => "Cooperativa Central de Crédito - Ailos",
    88_u16 => "Banco Randon S.A.",
    89_u16 => "Credisan Cooperativa de Crédito",
    91_u16 => "Central de Cooperativas de Economia e Crédito Mútuo do Estado do Rio Grande do Sul",
    92_u16 => "BRK S.A. Crédito, Financiamento e Investimento",
    94_u16 => "Banco Finaxis S.A.",
    95_u16 => "Travelex Banco de Câmbio S.A.",
    96_u16 => "Banco B3 S.A.",
    97_u16 => "Credisis - Central de Cooperativas de Crédito Ltda",
    98_u16 => "Credialiança Cooperativa de Crédito Rural",
    99_u16 => "Uniprime Central - Central Interestadual de Cooperativas de Crédito Ltda",
    100_u16 => "Planner Corretora de Valores S.A.",
    101_u16 => "Renascença Distribuidora de Títulos e Valores Mobiliários Ltda",
    102_u16 => "XP Investimentos Corretora de Câmbio,Títulos de Valores Mobiliários S.A.",
    104_u16 => "Caixa Econômica Federal",
    105_u16 => "Lecca Crédito",
    107_u16 => "Banco Bocom BBM S.A.",
    108_u16 => "PortoCred S.A. Crédito, Financiamento e Investimento",
    111_u16 => "Oliveira Trust Distribuidora de Títulos e Valores Mobiliários S.A.",
    113_u16 => "Magliano S.A. Corretora de Câmbio e Valores Mobiliários",
    114_u16 => "Central Cooperativa de Crédito no Estado do Espírito Santo - Cecoop",
    117_u16 => "Advanced Corretora de Câmbio Ltda",
    119_u16 => "Banco Western Union do Brasil S.A.",
    120_u16 => "Banco Rodobens S.A.",
    121_u16 => "Banco Agibank S.A.",
    122_u16 => "Banco Bradesco Berj S.A.",
    124_u16 => "Banco Woori Bank do Brasil S.A.",
    125_u16 => "Plural S.A. Banco Múltiplo",
    126_u16 => "Br Partners Banco de Investimento S.A.",
    127_u16 => "Codepe Corretora de Valores e Câmbio S.A.",
    128_u16 => "MS Bank S.A. Banco de Câmbio",
    129_u16 => "UBS Brasil Banco de Investimento S.A.",
    130_u16 => "Caruana S.A. - Sociedade de Crédito",
    131_u16 => "Tullett Prebon Brasil Corretora de Valores e Câmbio Ltda",
    132_u16 => "ICBC do Brasil Banco Múltiplo S.A.",
    133_u16 => "Banco Cresol - Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Solidária",
    134_u16 => "BGC Liquidez Distribuidora de Títulos e Valores Mobiliários Ltda",
    136_u16 => "Unicred do Brasil - Confederação Nacional das Cooperativas Centrais Unicred Ltda",
    138_u16 => "Get Money Corretora de Câmbio S.A.",
    139_u16 => "Intesa Sanpaolo Brasil S.A. - Banco Múltiplo",
    140_u16 => "Easynvest - Título Corretora de Valores S.A.",
    142_u16 => "Broker Brasil Corretora de Câmbio Ltda",
    143_u16 => "Treviso Corretora de Câmbio S.A.",
    144_u16 => "Bexs Banco de Câmbio S.A.",
    145_u16 => "Levycam - Corretora de Câmbio e Valores Ltda",
    146_u16 => "Guitta Corretora de Câmbio Ltda",
    149_u16 => "Facta Financeira S.A. - Crédito Financiamento e Investimento",
    157_u16 => "ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda",
    159_u16 => "Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor",
    163_u16 => "Commerzbank Brasil S.A. - Banco Múltiplo",
    169_u16 => "Banco Olé Consignado S.A.",
    173_u16 => "BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.",
    174_u16 => "Pefisa S.A. - Crédito",
    177_u16 => "Guide Investimentos S.A. Corretora de Valores",
    180_u16 => "CM Capital Markets Corretora de Câmbio, Títulos e Valores Mobiliários Ltda",
    183_u16 => "Socred S.A. - Sociedade de Crédito ao Microempreendedor e a Empresa de Pequeno Porte",
    184_u16 => "Banco Itaú BBA S.A.",
    188_u16 => "Ativa Investimentos S.A. Corretora de Títulos, Câmbio e Valores",
    189_u16 => "HS Financeira S.A. Crédito",
    190_u16 => "Servicoop - Cooperativa de Crédito dos Servidores Públicos Estaduais do Rio Grande do Sul",
    191_u16 => "Nova Futura Corretora de Títulos e Valores Mobiliários Ltda",
    194_u16 => "Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda",
    196_u16 => "Fair Corretora de Câmbio S.A.",
    197_u16 => "Stone Pagamentos S.A.",
    208_u16 => "Banco BTG Pactual S.A.",
    212_u16 => "Banco Original S.A.",
    213_u16 => "Banco Arbi S.A.",
    217_u16 => "Banco John Deere S.A.",
    218_u16 => "Banco BS2 S.A.",
    222_u16 => "Banco Crédit Agricole Brasil S.A.",
    224_u16 => "Banco Fibra S.A.",
    233_u16 => "Banco Cetelem S.A.",
    237_u16 => "Banco Bradesco S.A.",
    241_u16 => "Banco Classico S.A.",
    243_u16 => "Banco Máxima S.A.",
    246_u16 => "Banco ABC Brasil S.A.",
    249_u16 => "Banco Investcred Unibanco S.A.",
    250_u16 => "BCV - Banco de Crédito e Varejo S.A.",
    253_u16 => "Bexs Corretora de Câmbio S.A.",
    254_u16 => "Paraná Banco S.A.",
    259_u16 => "Moneycorp Banco de Câmbio S.A.",
    260_u16 => "Nu Pagamentos S.A.",
    265_u16 => "Banco Fator S.A.",
    266_u16 => "Banco Cédula S.A.",
    268_u16 => "Bari Companhia Hipotecária",
    269_u16 => "Banco HSBC S.A.",
    270_u16 => "Sagitur Corretora de Câmbio Ltda",
    271_u16 => "IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.",
    272_u16 => "AGK Corretora de Câmbio S.A.",
    273_u16 => "Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel",
    274_u16 => "Money Plus Sociedade de Crédito ao Microempreendedor e a Empresa de Pequeno Porte",
    276_u16 => "Senff S.A. - Crédito",
    278_u16 => "Genial Investimentos Corretora de Valores Mobiliários S.A.",
    279_u16 => "Cooperativa de Crédito Rural de Primavera do Leste",
    280_u16 => "Avista S.A. Crédito",
    281_u16 => "Cooperativa de Crédito Rural Coopavel",
    283_u16 => "RB Capital Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda",
    285_u16 => "Frente Corretora de Câmbio Ltda",
    286_u16 => "Cooperativa de Crédito Rural de Ouro Sulcredi/Ouro",
    288_u16 => "Carol Distribuidora de Títulos e Valores Mobiliários Ltda",
    289_u16 => "Decyseo Corretora de Câmbio Ltda",
    290_u16 => "Pagseguro Internet S.A.",
    292_u16 => "BS2 Distribuidora de Títulos e Valores Mobiliários S.A.",
    293_u16 => "Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda",
    296_u16 => "Vision S.A. Corretora de Câmbio",
    298_u16 => "Vip's Corretora de Câmbio Ltda",
    299_u16 => "Sorocred Crédito",
    300_u16 => "Banco de La Nacion Argentina",
    301_u16 => "BPP Instituição de Pagamento S.A.",
    306_u16 => "Portopar Distribuidora de Títulos e Valores Mobiliários Ltda",
    309_u16 => "Câmbionet Corretora de Câmbio Ltda",
    310_u16 => "Vortx Distribuidora de Títulos e Valores Mobiliários Ltda",
    313_u16 => "Amazônia Corretora de Câmbio Ltda",
    315_u16 => "Pi Distribuidora de Títulos e Valores Mobiliários S.A.",
    318_u16 => "Banco BMG S.A.",
    319_u16 => "OM Distribuidora de Títulos e Valores Mobiliários Ltda",
    320_u16 => "China Construction Bank (Brasil) Banco Múltiplo S.A.",
    321_u16 => "Crefaz Sociedade de Crédito ao Microempreendedor e a Empresa de Pequeno Porte Ltda",
    322_u16 => "Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz",
    323_u16 => "MercadoPago.com Representações Ltda",
    324_u16 => "Cartos Sociedade de Crédito Direto S.A.",
    325_u16 => "Órama Distribuidora de Títulos e Valores Mobiliários S.A.",
    326_u16 => "Parati - Crédito",
    329_u16 => "Qi Sociedade de Crédito Direto S.A.",
    330_u16 => "Banco Bari de Investimentos e Financiamentos S.A.",
    331_u16 => "Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.",
    332_u16 => "Acesso Soluções de Pagamento S.A.",
    335_u16 => "Banco Digio S.A.",
    336_u16 => "Banco C6 S.A.",
    340_u16 => "Super Pagamentos e Administração de Meios Eletrônicos S.A.",
    341_u16 => "Itaú Unibanco S.A.",
    342_u16 => "Creditas Sociedade de Crédito Direto S.A.",
    343_u16 => "FFA Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda",
    348_u16 => "Banco XP S.A.",
    349_u16 => "Al5 S.A. Crédito",
    352_u16 => "Toro Corretora de Títulos e Valores Mobiliários Ltda",
    354_u16 => "Necton Investimentos S.A. Corretora de Valores Mobiliários e Commodities",
    355_u16 => "Ótimo Sociedade de Crédito Direto S.A.",
    359_u16 => "Zema Crédito",
    362_u16 => "Cielo S.A.",
    363_u16 => "Socopa Sociedade Corretora Paulista S.A.",
    364_u16 => "Gerencianet S.A.",
    365_u16 => "Solidus S.A. Corretora de Câmbio e Valores Mobiliários",
    366_u16 => "Banco Société Générale Brasil S.A.",
    367_u16 => "Vitreo Distribuidora de Títulos e Valores Mobiliários S.A.",
    368_u16 => "Banco CSF S.A.",
    370_u16 => "Banco Mizuho do Brasil S.A.",
    373_u16 => "UP.P Sociedade de Empréstimo Entre Pessoas S.A.",
    374_u16 => "Realize Crédito",
    376_u16 => "Banco J.P. Morgan S.A.",
    378_u16 => "BBC Leasing S.A. - Arrendamento Mercantil",
    380_u16 => "PicPay Serviços S.A.",
    381_u16 => "Banco Mercedes-Benz do Brasil S.A.",
    384_u16 => "Global Finanças - Sociedade de Crédito ao Microempreendedor e a Empresa de Pequeno Porte Ltda",
    387_u16 => "Banco Toyota do Brasil S.A.",
    389_u16 => "Banco Mercantil do Brasil S.A.",
    390_u16 => "Banco GM S.A.",
    391_u16 => "Cooperativa de Crédito Rural de Ibiam - Sulcredi/Ibiam",
    393_u16 => "Banco Volkswagen S.A.",
    394_u16 => "Banco Bradesco Financiamentos S.A.",
    396_u16 => "Hub Pagamentos S.A",
    397_u16 => "Listo Sociedade de Crédito Direto S.A.",
    399_u16 => "Kirton Bank S.A. - Banco Múltiplo",
    403_u16 => "Cora Sociedade de Crédito Direto S.A.",
    404_u16 => "Sumup Sociedade de Crédito Direto S.A.",
    408_u16 => "Bónuscred Sociedade de Crédito Direto S.A.",
    412_u16 => "Banco Capital S.A.",
    422_u16 => "Banco Safra S.A.",
    456_u16 => "Banco MUFG Brasil S.A.",
    464_u16 => "Banco Sumitomo Mitsui Brasileiro S.A.",
    473_u16 => "Banco Caixa Geral - Brasil S.A.",
    477_u16 => "Citibank N.A.",
    479_u16 => "Banco Itaubank S.A.",
    487_u16 => "Deutsche Bank S.A.",
    488_u16 => "JPMorgan Chase Bank",
    492_u16 => "ING Bank N.V.",
    495_u16 => "Banco de La Provincia de Buenos Aires",
    505_u16 => "Banco Credit Suisse (Brasil) S.A.",
    545_u16 => "Senso Corretora de Câmbio e Valores Mobiliários S.A",
    600_u16 => "Banco Luso Brasileiro S.A.",
    604_u16 => "Banco Industrial do Brasil S.A.",
    610_u16 => "Banco VR S.A.",
    611_u16 => "Banco Paulista S.A.",
    612_u16 => "Banco Guanabara S.A.",
    613_u16 => "Omni Banco S.A.",
    623_u16 => "Banco Pan S.A.",
    626_u16 => "Banco C6 Consignado S.A.",
    630_u16 => "Banco Smartbank S.A.",
    633_u16 => "Banco Rendimento S.A.",
    634_u16 => "Banco Triângulo S.A.",
    637_u16 => "Banco Sofisa S.A.",
    643_u16 => "Banco Pine S.A.",
    652_u16 => "Itaú Unibanco Holding S.A.",
    653_u16 => "Banco Indusval S.A.",
    654_u16 => "Banco Digimais S.A.",
    655_u16 => "Banco Votorantim S.A.",
    707_u16 => "Banco Daycoval S.A.",
    712_u16 => "Banco Ourinvest S.A.",
    739_u16 => "Banco Cetelem S.A.",
    741_u16 => "Banco Ribeirão Preto S.A.",
    743_u16 => "Banco Semear S.A.",
    745_u16 => "Banco Citibank S.A.",
    746_u16 => "Banco Modal S.A.",
    747_u16 => "Banco Rabobank International Brasil S.A.",
    748_u16 => "Banco Cooperativo Sicredi S.A.",
    751_u16 => "Scotiabank Brasil S.A. Banco Múltiplo",
    752_u16 => "Banco BNP Paribas Brasil S.A.",
    753_u16 => "Novo Banco Continental S.A. - Banco Múltiplo",
    754_u16 => "Banco Sistema S.A.",
    755_u16 => "Bank of America Merrill Lynch Banco Múltiplo S.A.",
    756_u16 => "Banco Cooperativo do Brasil S.A. - Bancoob - Sicoob",
    757_u16 => "Banco Keb Hana do Brasil S.A.",
};

static DEFAULT_NAME: &str = "Banco não encontrado";

#[allow(dead_code)]
#[derive(Debug)]
pub struct InfoBanco {
    id: u16,
    nome: &'static str,
}

impl fmt::Display for InfoBanco {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[{:03}] {}", self.id, self.nome)
    }
}

impl InfoBanco {
    pub fn get_by_id(id: u16) -> InfoBanco {
        match BANKS_INFO.get(&id) {
            Some(nome) => InfoBanco { id, nome },
            None => InfoBanco { id, nome: DEFAULT_NAME },
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::instituicoes_bancarias::BANKS_INFO;

    use super::InfoBanco;

    #[test]
    fn should_load_and_get_info_bancos() {
        let info = InfoBanco::get_by_id(0);
        assert!(matches!(info, InfoBanco { id: _, nome: DEFAULT_NAME }));

        println!("HashMap.len() == {}", BANKS_INFO.len());

        let info = InfoBanco::get_by_id(1);
        assert_eq!(info.id, 1);
        assert!(info.nome.contains("Banco do Brasil"));

        let info = InfoBanco::get_by_id(341);
        assert_eq!(info.id, 341);
        assert!(info.nome.contains("Itaú"));

        let info = InfoBanco::get_by_id(655);
        assert_eq!(info.id, 655);
        assert!(info.nome.contains("Votorantim"));
    }
}
